apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-clusterapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster-gitops
  source:
    repoURL: git@github.com:susikanth/argo-app.git
    targetRevision: main
    path: applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
