apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
spec:
  args:
  - name: rollout-acs
  metrics:
  - name: error-rate
    interval: 5m
    successCondition: result[0] <= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://eks-dev-m2p-monitoring-sta-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(irate(
            nginx_ingress_controller_requests{ingress=~"{{args.ingress-name}}",status=~"5.*"}[5m]
          )) /
          sum(irate(
            nginx_ingress_controller_requests{ingress=~"{{args.ingress-name}}"}[5m]
          ))
