apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
  namespace: argocd
spec:
  args:
  - name: service-name
  metrics:
  - name: success-count
    interval: 5m
    successCondition: result[0] <= 1
    failureLimit: 3
    provider:
      prometheus:
        address: http://eks-dev-m2p-monitoring-sta-prometheus.monitoring.svc.cluster.local:9090
        query: |
          sum(irate(nginx_ingress_controller_requests {exported_service= "acs-portal", host= "dev-monitoring.m2pfintech.com", status=~"^[3-5].."}[1m]))