apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rollout-acs
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.teams: argocd
    notifications.argoproj.io/subscribe.on-sync-failed.teams: argocd
    notifications.argoproj.io/subscribe.on-health-degraded.teams: argocd
spec:  
  generators:
  - list:
      elements:
      - cluster: in-cluster
        name: in-cluster 
      
  template:
    metadata:
      name: 'rollout-{{name}}'
    spec:
      project: "rollout-test"
      source:
        repoURL: git@github.com:susikanth/argo-app.git
        targetRevision: main
        path: 'acs'
      destination:
        name: '{{name}}'
        namespace: 'argo'
      syncPolicy:
        syncOptions:    
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
